### ISSUE TITLE
Test-only implementation fails

### ISSUE THREAD

**Issue by lpender** [thoughtbot/ex_machina#403] opened 2020-11-13 20:35 UTC
The Readme mentions:

## Install in just the test environment with Phoenix:

In mix.exs, add the ExMachina dependency:

```
def deps do
  [
    {:ex_machina, "~> 2.4", only: :test},
  ]
end
```

However, doing this creates the following issue once you've implemented a `factory.ex` file

```
== Compilation error in file lib/risc/factory.ex ==
** (CompileError) lib/risc/factory.ex:2: module ExMachina.Ecto is not loaded and could not be found
```

**Comment by germsvel** [comment] 2020-12-19 10:29
Hi @lpender, thanks for opening this issue. I am unable to reproduce the error the way you've defined it. Could you provide some more information on how to reproduce it? What does your `factory.ex` module look like?

**Comment by germsvel** [comment] 2021-02-02 09:50
@lpender I'm gonna close this issue since I imagine you got it resolved. But if I'm mistaken, please feel free to comment here and we can reopen it.

**Closed by germsvel** 2021-02-02 09:50 UTC

**Comment by lpender** [comment] 2021-02-02 18:23
Hi,

Thanks,

I'm using the Dockerfile described in the [Phoenix Documentation](https://hexdocs.pm/phoenix/releases.html#containers).

Notably, because `Mix` is a build tool, many things fail with this setup, i.e. any calls to `Mix.env()` in runtime code (which I see for example, in the default `router.ex` generated by Phoenix and in [constable](https://github.com/thoughtbot/constable)).

This is puzzling to me, but I digress.

I'm still running into this issue.

```
# mix.exs
  defp deps do
      {:ex_machina, "~> 2.4", only: :test}
  end
```

```
# lib/risc/factory.ex

defmodule Risc.Factory do
  use ExMachina.Ecto, repo: Risc.Repo

  def account_factory do
    %Risc.Accounts.Account{
      email: sequence(:email, &"email-#{&1}@example.com"),
      password: "sooperdoopersecret"
    }
  end
end
```

Docker Compilation:

```
Step 17/25 : RUN mix do compile, release
 ---> Running in c6748e8c0dd3
Compiling 34 files (.ex)
== Compilation error in file lib/risc/factory.ex ==
** (CompileError) lib/risc/factory.ex:2: module ExMachina.Ecto is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/2
    lib/risc/factory.ex:2: Risc.Factory (module)
```

This error doesn't happen if I remove the `only: :test` but that causes the `mix compile,release` command to fail with a different error:

```
Cannot read "/app/_build/prod/rel/my_app/releases/0.1.0/start.script
```

**Comment by lpender** [comment] 2021-02-02 18:25
Update:

The solution for this is to move the `factory.ex` file from `lib/my_app/factory.ex` to `test/support/factory.ex`.

I see now that the README says to do this now.

I was confused because I was following constable.

We can leave this closed, just posting for future generations.
