### ISSUE TITLE
Getting ** (CaseClauseError) no case clause matching: {:id, :id, :id}

### ISSUE THREAD

**Issue by MrCoffey** [thoughtbot/ex_machina#240] opened 2017-08-23 21:26 UTC
Hi guys! I am receiving the following error while running my test after upgrading my elixir version from 1.4 to 1.5.1, nevertheless, I couldn't be able to make things run again even after downgrade the elixir version and cleaning the cache by deleting the `_build` and `deps` folders.

```
  1) test deliver/2 returns an {:ok, "ok"} tuple (Notifications.WebHook.PerformTest)
     test/webhook/perform_test.exs:22
     ** (CaseClauseError) no case clause matching: {:id, :id, :id}
     code: organization_hook = insert(:organization_hook)
     stacktrace:
       (ex_machina) lib/ex_machina/ecto.ex:253: ExMachina.Ecto.drop_autogenerated_ids/2
       (ex_machina) lib/ex_machina/ecto_strategy.ex:37: ExMachina.EctoStrategy.cast_all_fields/1
       (ex_machina) lib/ex_machina/ecto_strategy.ex:31: ExMachina.EctoStrategy.cast/1
       (ex_machina) lib/ex_machina/ecto_strategy.ex:17: ExMachina.EctoStrategy.handle_insert/2
       test/webhook/perform_test.exs:23: (test)
```

This is happening using any of the following lines

```
insert(:organization_hook)
```
or

```
OrganizationHooks.changeset(%OrganizationHooks{}, params_for(:organization_hook))
```

or even

```
params_for(:vehicle_track)
```
Those lines and others were working before. Reviewing the function [involved](https://github.com/thoughtbot/ex_machina/blob/v2.0.0/lib/ex_machina/ecto.ex#L253), I saw that the case statement does not handle the `{:id, :id, :id}` tuple. It works after a bit of handcrafting:

```
  defp drop_autogenerated_ids(map, struct) do
    case struct.__schema__(:autogenerate_id) do
      nil -> map
      {name, _type} -> Map.delete(map, name)
      _ -> map
    end
  end
```

I have to say that my solution might be a little bit poor or even I am doing something wrong. So would like to ask you guys for any thoughts in order to dive further and eventually create a PR if necessary.

Thank you in advance!

**Comment by boydm** [comment] 2017-08-24 01:46
I ran in to this as well. Your hack fixed it for me too.

**Comment by rhnonose** [comment] 2017-08-24 16:57
Same for me, the hack works.

**Comment by doomspork** [comment] 2017-08-25 22:22
Ran into this myself.  Looks like the issue is a result of using ex_machina with Ecto 2.2, the two PRs to add support #241 and #238 fix the issue.

@paulcsmith any chance of those being merged anytime soon?

**Comment by warmwaffles** [comment] 2017-08-30 17:30
#238 does solve the problem, and we need to cut a new release for this. Otherwise we have to depend on this git repo at the current master ref.

**Comment by paulcsmith** [comment] 2017-08-30 17:32
@doomspork yes, hoping to test it and get it out on Friday. I don't want to cut a new release without doing some testing on our projects first. That way we can be reasonably sure we didn't inadvertently introduce any new issues

**Comment by warmwaffles** [comment] 2017-08-30 17:34
Cool, yea I tested this out on our umbrella application with ecto `2.2.1` and it resolved this issue that was cropping up. Can you mention me when you cut a release @paulcsmith?

**Comment by paulcsmith** [comment] 2017-08-30 17:35
@warmwaffles I will try to remember, but if you subscribe to this issue you will be notified when it closes 👍

**Comment by warmwaffles** [comment] 2017-08-30 17:35
Cool, thanks!

**Comment by jsteiner** [comment] 2017-08-30 18:03
There is also https://tellmewhenitcloses.com for people who want to be
notified when the issue closes but don't care about all the comments.

**Comment by yordis** [comment] 2017-08-31 01:18
Could someone from `thoughtbot` could publish some `beta` version to Hex?

I can't upgrade non of my packages because of this, it will break with the latest `ecto` version

**Comment by yordis** [comment] 2017-08-31 21:29
@paulcsmith hey mate, could you at least publish some `beta` version to Hex? Tests are passing!

It wouldn't take you that much and will help a lot of people like me. I really need this upgrade for be able to run my test and worst for me, I have deadline to meet 😢  I really need your support on this, please.

**Comment by paulcsmith** [comment] 2017-08-31 21:34
@yordis I will put it up on hex soon. You can also use the version on master right now and it should work for you 👍 

```elixir
{:ex_machina, github: "thoughtbot/ex_machina"}
```

You may also want to consider holding off on upgrading Ecto until ExMachina is ready. Hoping to get it out soon though

**Comment by yordis** [comment] 2017-08-31 21:41
@paulcsmith I would do that but have more side effects than take 2 minutes for publish a `beta` version to Hex.

Hex will download the hold `github project`, also just imagine that somebody break the package in the next commit, I can't control that once I pull from `master`

I know I could do that, but once again, I am asking for some `beta` version, it wouldn't hurt and takes you little time for that. I don't see what is the problem with that, so people who want to use `beta` version understand what is going on and take the responsibility. 

Just be on my position for a moment please, it's 2 minutes from your side vs a lot of side effects from your proposal. Please.

**Comment by yordis** [comment] 2017-08-31 21:44
Also from March 3 you didn't release. Issues like `ex_machina` complaining about having `ecto` twice on the high level projects will be fix as well.

**Comment by paulcsmith** [comment] 2017-08-31 21:46
If you point to master it will lock it to the version currently there *until you explicitly update it*. Try it and take a look at mix.lock, you'll see it locks to a particular commit. It is a perfectly valid solution that can hold you over until tomorrow when I publish the full version. There is very little to gain by me doing a beta release only to do the real one tomorrow with no other changes.

Please be patient with me. It takes more than 2 mins because I have to go through commits and create a changelog. I *could* post without it, but I'd rather wait until tomorrow and do it right.

**Comment by rhnonose** [comment] 2017-08-31 23:45
@yordis you can lock to a commit explicitly in `mix.exs` like this as well:
`{:ex_machina, github: "thoughtbot/ex_machina", ref: "8f494f1"}`
This won't break even if you run `mix deps.get` again.

**Comment by paulcsmith** [comment] 2017-09-01 15:46
2.1.0 is up on hex! Feel free to give it a shot and open up an issue for anything you find

**Closed by paulcsmith** 2017-09-01 15:46 UTC
