### ISSUE TITLE
Read after writes for primary keys

### ISSUE THREAD

**Issue by mackeyja92** [thoughtbot/ex_machina#199] opened 2017-02-12 07:38 UTC
The factories aren't honoring `read_after_writes: true` for my schema's primary keys. My phoenix app is working correctly and running the correct SQL but my tests are not. I am very new to this stack so maybe I am missing something somewhere. 

Working SQL printed from phoenix server
```
INSERT INTO "todos" ("description","title","inserted_at","updated_at") VALUES ($1,$2,$3,$4) RETURNING "uuid" ["Test creation of todos via a post on '/api/todos/'", "Test Todo creation", {{2017, 2, 12}, {7, 13, 37, 879320}}, {{2017, 2, 12}, {7, 13, 37, 879326}}]
```

Schema:

```elixir
defmodule Todo.Schema do
  defmacro __using__(_) do
    quote do
        use Ecto.Schema
        @primary_key {:uuid, Ecto.UUID, read_after_writes: true}
        @foreign_key_type :uuid
    end
  end
end
```

Migration

```elixir
defmodule Todo.Repo.Migrations.CreateTodo do
  use Ecto.Migration

  def change do
    execute "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\""

    create table(:todos, primary_key: false) do
      add :uuid, :uuid, primary_key: true, default: fragment("uuid_generate_v1()")
      add :title, :string
      add :description, :text

      timestamps()
    end
  end
end
```

Factory

```elixir
defmodule Todo.Factory do
    use ExMachina.Ecto, repo: Todo.Repo

    def todo_factory do
      %Todo.Todo{
        title: "Something I need to do"
      }
    end
 end
```

Controller test

```elixir
defmodule Todo.TodoControllerTest do
  use Todo.ConnCase

  test "#index renders a list of todos" do
    conn = build_conn()
    todo = insert(:todo)

    conn = get conn, todo_path(conn, :index)
    assert json_response(conn, 200) == render_json(Todo.TodoView, "index.json", todos: [todo])
  end
```

Error running tests

```
1) test #index renders a list of todos (Todo.TodoControllerTest)
 test/controllers/todo_controller_test.exs:4
 ** (Postgrex.Error) ERROR 23502 (not_null_violation): null value in column "uuid" violates not-null constraint

     table: todos
     column: uuid

 Failing row contains (null, Something I need to do, null, 2017-02-12 07:17:23.701679, 2017-02-12 07:17:23.708057).
 stacktrace:
   (ecto) lib/ecto/adapters/sql.ex:570: Ecto.Adapters.SQL.struct/7
   (ecto) lib/ecto/repo/schema.ex:467: Ecto.Repo.Schema.apply/4
   (ecto) lib/ecto/repo/schema.ex:205: anonymous fn/13 in Ecto.Repo.Schema.do_insert/4
   (ecto) lib/ecto/repo/schema.ex:131: Ecto.Repo.Schema.insert!/4
   test/controllers/todo_controller_test.exs:6: (test)
```

**Comment by paulcsmith** [comment] 2017-02-24 15:30
@mackeyja92 I think read after writes would be fantastic to have in ExMachina, but since I don't currently use it and I'm busy maintaining this and other libraries I'm not sure when I can get to it. If you or someone else would like to take a stab at a Pull Request I'd be happy to review it!

Thanks!

**Comment by bozydar** [comment] 2017-02-27 13:51
@mackeyja92  I made some tests and it looks like there is no problem with ex_machina. https://github.com/bozydar/ex_machina/commit/7a00a7f7b73d44706aad2bbd80d686cc6cb926e7
All tests have passed.
I even went further and extracted the schema like you.
https://github.com/bozydar/ex_machina/commit/7f9ee54dc230375051a53cb7c673979b451f836d
And it still worked.

**Comment by paulcsmith** [comment] 2017-02-27 16:04
Thank you so much @bozydar! Looks like the issue is probably with @mackeyja92's application. @mackeyja92 I'm going to go ahead and close this, but if you still have issues be sure to try out `master` first (`{:ex_machina, github: "thoughtbot/ex_machina", branch: "master"}` and if it still doesn't work, please add a failing test so we can take a closer look.

**Closed by paulcsmith** 2017-02-27 16:04 UTC
Labels: help wanted
