### ISSUE TITLE
Automatically cast datetimes?

### ISSUE THREAD

**Issue by henrik** [thoughtbot/ex_machina#54] opened 2015-11-08 16:53 UTC
I had(?) to do this:

``` elixir
  def factory(:package, _attrs) do
    {:ok, time} = Ecto.DateTime.cast({{2001, 2, 3}, {4, 5, 6}})

    %Package{
      hex_updated_at: time,
    }
```

Would be nice if you could just pass a string like `"2001-02-03T04:05:06Z"` and it would be automatically cast.

Casting happens if you do

``` elixir
Repo.insert! Package.changeset(%Package{}, %{name: "my_package", description: "My package.", hex_updated_at: my_time_string})
```

for example.

**Comment by paulcsmith** [comment] 2015-11-09 17:46
I'll have to look into this more. Under the hood ExMachina uses changesets, so it might not be hard to also cast all the fields. I'm not totally sure ExMachina should handle this, but I'll think about it.

**Comment by henrik** [comment] 2015-11-09 19:45
Thank you :) I think dates/times in factories might be a bit painful otherwise – though maybe there's a nicer way than what I did.

**Comment by paulcsmith** [comment] 2015-11-09 19:48
In the meantime you could simplify this by extracting a private function and calling [`Ecto.DateTime.cast`](http://hexdocs.pm/ecto/Ecto.DateTime.html#cast/1)

```elixir
def factory(:package, _attrs) do
  %Package{
    hex_update_at: date_time("2001-02-03T04:05:06Z")
  }
end

defp date_time(date_time) do
  Ecto.DateTime.cast(date_time)
end
```

**Comment by henrik** [comment] 2015-11-09 20:59
@paulcsmith Good idea, thank you.

I'll sneak this in here since it's quite related: I'm unable to get this working for passed-in dates.

I tried this:

``` elixir
  def factory(:package, attrs) do
    time = Dict.get(attrs, :hex_updated_at, "2001-02-03T04:05:06Z")
    {:ok, cast_time} = Ecto.DateTime.cast(time)

    %Package{
      name: sequence(:name, &"package#{&1}"),
      description: "A package.",
      hex_updated_at: cast_time,
    }
  end
```

The default value is cast OK, but if I pass in a custom value, it is not cast. I debugged a bit and it seems the `changes` changeset that `ExMachina.Ecto.save_record/3` gets does indeed not have the cast value. I guess I'm misunderstanding something about how you're meant to customize attributes if you also want to massage them a bit.

**Comment by paulcsmith** [comment] 2015-11-09 21:03
@henrik Ah yes, that is a good point. The problem is that the cast attribute is overridden because the `attrs` are merged in after the `factory/2` function is called. You can do what I said with a hard-coded binary, but if it's from the `attrs` it won't work unless you custom the `save_record` function to cast the changes with Ecto.Changeset.cast. 

The more I think about it, the more it seems like this should be part of ExMachina.Ecto. I'll probably add it this week or next. Unless you want to try to tackle it in a PR :) I think it just needs to get the changes and pass them through Ecto.Changeset.cast.

**Comment by henrik** [comment] 2015-11-09 21:08
Oh yeah, I just found that part of the code. This bit, right?

``` elixir
  def build(module, factory_name, attrs \\ %{}) do
    attrs = Enum.into(attrs, %{})
    module.factory(factory_name, attrs) |> Map.merge(attrs)
  end
```

**Comment by henrik** [comment] 2015-11-09 21:10
I would love to tackle it in a PR, but I'm hard-pressed to find time for the project I'm actually trying to work on, so I don't think I'll have the time to spare until that's done :/ I'll customize `save_record` for now – good idea.

**Comment by paulcsmith** [comment] 2015-11-09 21:21
No problem, I totally understand. Yes that's the bit that merges the parameters and overrides your cast one. Good luck with your project :)

**Comment by paulcsmith** [comment] 2015-11-13 18:22
I started work on this, but it relies on https://github.com/elixir-lang/ecto/pull/1081 before I can get it working with associations. Once a new version of Ecto is released I can pick this work up again

**Comment by paulcsmith** [comment] 2016-01-27 16:16
I'm going to check this when Ecto 2.0 comes out to see if it is handled automatically when you call `Repo.insert!`. That would be the most ideal solution, but if that doesn't work I'll try to come up with something else. I do agree that automatically casting would be a lot nicer. That way you can give it an erlang time from GoodTimes (as an example) and it would cast it correctly without having to do explicit conversion every time

**Comment by paulcsmith** [comment] 2016-02-03 16:51
Chatted with @josevalim about this on IRC

> [11:42:03] <paulcsmith_>	josevalim Hmm, any ideas on how to handle this? https://github.com/thoughtbot/ex_machina/issues/54 basically, it would be nice if you could set a datetime with an erlang datetime, but you have to manually cast it somewhere, either in the factory or when setting the attrs
> [11:42:19]  <paulcsmith_>	And if you don't have time, no worries :) 
> [11:43:40]  <paulcsmith_>	Maybe I could cast everything and then call apply_changes before passing the record to Repo.insert. That's the first thing that comes to mind that might work. Not sure of the ramifications though
> [11:44:31]  <josevalim>	paulcsmith_: i would say you should pass the proper value in
> [11:44:45]  <josevalim>	paulcsmith_: datetime(....) when you call the factory
> [11:44:49]  <josevalim>	paulcsmith_: won't hurt
> [11:45:03]  <josevalim>	build(:package, inserted_at: datetime("...."))
> [11:45:07]  <josevalim>	can even make it a sigil
> [11:45:09]  <josevalim>	~d(...)
> [11:45:12]  <paulcsmith_>	Yeah that might be the best option. It's what I'm doing now and it does work :)
> [11:45:24]  <paulcsmith_>	Oh the sigil idea sounds interesting. I'll have to try that out.
> [11:45:27]  <paulcsmith_>	Thanks for the input :)

To sum up, the best option might be to add the `datetime` function as mentioned [here](https://github.com/thoughtbot/ex_machina/issues/54#issuecomment-155170729) to your factory, or add a sigil that does that for you. You'd probably want to make it a public function though so it could be used in your tests to override attributes: `build(:package, inserted_at: datetime(GoodTimes.a_day_ago))`

I'm considering adding a sigil to ExMachina.Ecto that you could optionally import, but it might be simple enough to just do on your own and we could add it to the README instead.

Does this help @henrik?

**Comment by paulcsmith** [comment] 2016-02-03 21:48
I'm going to close this in favor of #94. Let me know if you have any further feedback on the other issue please :)

**Closed** 2016-02-10 19:01 UTC
