### ISSUE TITLE
warning: the dependency :ecto is duplicated at the top level, please remove one of them

### ISSUE THREAD

**Issue by digitalcake** [thoughtbot/ex_machina#234] opened 2017-07-30 19:39 UTC
I have a new app and after trying to compile I get
```
Compiling 1 file (.ex)
==> ex_machina
warning: the dependency :ecto is duplicated at the top level, please remove one of them
warning: the dependency :ecto is duplicated at the top level, please remove one of them
```

Thoughts?

Also removing ex_machina fixes the compile

my specs:
Erlang/OTP 20 [erts-9.0]
Elixir (1.5.0)
Phoenix 1.3

**Comment by digitalcake** [comment] 2017-07-30 20:07
adding only: :test allows me to compile without the error

**Comment by jsteiner** [comment] 2017-08-02 14:49
This is a duplicate of https://github.com/thoughtbot/ex_machina/pull/208 and should be fixed when we release the next version.

**Closed by jsteiner** 2017-08-02 14:49 UTC
